# We defined stages here, so we can dynamic change the flow in future.

stages:
  - initial
  - scan
  - build
  - deploy
  - test
  - userjobs

workflow:
  # Rule will replaced if project have their customized workflow, otherwise it will be used as default.
  rules:
    - if: $GITLAB_USER_LOGIN == "root"
      when: never
    - when: always # Always run pipeline for other cases
